### PR TITLE
Rename ros_lib folder

### PR DESCRIPTION
**Pull request by eborghi10**
Folder renamed: from `rosabridge_arduino/sketchbook/libraries/ros_lib/rosproxy_msgs` to `../ros_lib/rosabridge_msgs`.

### CODE REVIEW

**Comment by attermann** [comment]
Hi @eborghi10.  Will you please elaborate on the purpose of the path change?  Is it for convenience to aid in building?  My immediate concern with the proposed change is that it does not reflect the fact that these are Arduino libs as opposed to another uC implementation.  Granted Arduino is probably the only present use, it does not preclude the use on other uC platforms.

**Comment by eborghi10** [comment]
In the second line of the instructions, [here](https://github.com/ecostech/rosabridge#usage), says that the ros_lib messages folder has the name rosabridge_msgs and, also, if you compile one of the Arduino examples, you will have an error because the IDE doesn't find the `rosabridge_msgs`. That's because the current folder is called `rosproxy_msgs`.

**Comment by attermann** [comment]
Ah OK, I understand.  I didn't catch the "../" in your paths.  This is great.  I will commit your changes now.

**Comment by attermann** [comment]
Merge complete.  Thanks for your contribution!

**Comment by eborghi10** [comment]
Your welcome!

**Pull request merged**
